INSERT INTO UNITAT VALUES(1,'GRAMS');
INSERT INTO UNITAT VALUES(2,'KILOGRAMS');
INSERT INTO UNITAT VALUES(3,'LITRES');
INSERT INTO UNITAT VALUES(4,'UNITATS');
INSERT INTO UNITAT VALUES(5,'CULLERETA');
INSERT INTO UNITAT VALUES(6,'CULLERA');

INSERT INTO INGREDIENT VALUES(1,'OUS');
INSERT INTO INGREDIENT VALUES(2,'TONYINA');
INSERT INTO INGREDIENT VALUES(3,'ENTRECOT_VEDELLA');
INSERT INTO INGREDIENT VALUES(4,'SAL');
INSERT INTO INGREDIENT VALUES(5,'PEBRE');
INSERT INTO INGREDIENT VALUES(6,'PATATES');
INSERT INTO INGREDIENT VALUES(7,'FARINA');
INSERT INTO INGREDIENT VALUES(8,'CIGRONS');
INSERT INTO INGREDIENT VALUES(9,'LLENTIES');
INSERT INTO INGREDIENT VALUES(10,'OLI');
INSERT INTO INGREDIENT VALUES(11,'MONGETES');
INSERT INTO INGREDIENT VALUES(12,'BUTIFARA');
INSERT INTO INGREDIENT VALUES(13,'ALL');
INSERT INTO INGREDIENT VALUES(14,'JULIBERT');
INSERT INTO INGREDIENT VALUES(15,'LLOM');
INSERT INTO INGREDIENT VALUES(16,'PA');
INSERT INTO INGREDIENT VALUES(17,'PERNIL');
INSERT INTO INGREDIENT VALUES(18,'FORMATGE');
INSERT INTO INGREDIENT VALUES(19,'LLIMONA');
INSERT INTO INGREDIENT VALUES(20,'LLAGOSTINS');
INSERT INTO INGREDIENT VALUES(21,'SALMÓ');
INSERT INTO INGREDIENT VALUES(22,'PIT_POLLASTRE');
INSERT INTO INGREDIENT VALUES(23,'RUCULA');
INSERT INTO INGREDIENT VALUES(24,'TOMAQUET');
INSERT INTO INGREDIENT VALUES(25,'SAITÀ');
INSERT INTO INGREDIENT VALUES(26,'ARRÒS');

INSERT INTO CATEGORIA VALUES (1,'CARN','#FF3333');
INSERT INTO CATEGORIA VALUES (2,'PEIX','#33FFFC');
INSERT INTO CATEGORIA VALUES (3,'JAPONES','#FCFF33');
INSERT INTO CATEGORIA VALUES (4,'VEGÀ','#68FF33');

INSERT INTO PLAT VALUES (1,'Entrecot a la Brasa','350 grams de entrecot fet a la brasa amb guarnicio de patates amb all i oli',20.99,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/entrecot.jpg'),true,1);
INSERT INTO PLAT VALUES (2,'Llagostins a la Brasa','Llagostins de palamòs a la brasa amb all i julibert',10.50,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/llagostins.jpg'),true,2);
INSERT INTO PLAT VALUES (3,'Sashami de tonyina','10 unitats de Sashami de tonyina',16.20,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/sashimi.jpg'),true,3);
INSERT INTO PLAT VALUES (4,'Mongetes amb butifarra','Butifara del país feta a la brasa amb guarnició de mongetes i all i oli',10.20,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/buti.jpg'),true,1);
INSERT INTO PLAT VALUES (5,'Llom arrebosat amb cigrons','Llom arrebosat amb formatge amb guarnició de cigrons',12.45,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/llom.jpg'),true,1);
INSERT INTO PLAT VALUES (6,'Pit de pollastre amb llenties','Pit de pollastre fet a la brasa amb guarnició de llenties',10.15,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/pollo.jpg'),true,1);
INSERT INTO PLAT VALUES (7,'Salmó a la planxa','Salmó fresc a la planxa amb guarnició de rucula i tomàquet',10.15,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/salmo.jpg'),true,2);
INSERT INTO PLAT VALUES (8,'Nigiri de tonyina','2 unitats de Nigiri de tonyina',3.50,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/nigiriTun.jpg'),true,3);
INSERT INTO PLAT VALUES (9,'Nigiri de salmó','2 unitats de Nigiri de salmó',3.30,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/nigiriSalmo.jpg'),true,3);
INSERT INTO PLAT VALUES (10,'Ensortit formatge i pernil','Pa torrat amb tomàquet i ensortit de pernil formatge',9.50,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/paPernil.jpg'),true,1);
INSERT INTO PLAT VALUES (11,'Saità a la planxa','Saità a la planxa amb guarnició de patates i rucula',13.50,LOAD_FILE('D:/cromp/2n DAM/Projecte/Imatges/saita.jpg'),true,4);

INSERT INTO LINIA_ESCANDALL VALUES(1,1,350,1,3);
INSERT INTO LINIA_ESCANDALL VALUES(1,2,1,5,4);
INSERT INTO LINIA_ESCANDALL VALUES(1,3,1,5,5);
INSERT INTO LINIA_ESCANDALL VALUES(1,4,5,4,6);
INSERT INTO LINIA_ESCANDALL VALUES(1,5,1,4,1);
INSERT INTO LINIA_ESCANDALL VALUES(1,6,15,6,10);
INSERT INTO LINIA_ESCANDALL VALUES(1,7,1,4,13);

INSERT INTO LINIA_ESCANDALL VALUES(2,1,6,4,20);
INSERT INTO LINIA_ESCANDALL VALUES(2,2,1,4,13);
INSERT INTO LINIA_ESCANDALL VALUES(2,3,2,6,14);

INSERT INTO LINIA_ESCANDALL VALUES(3,1,200,1,2);

INSERT INTO LINIA_ESCANDALL VALUES(4,1,1,4,12);
INSERT INTO LINIA_ESCANDALL VALUES(4,2,200,1,11);
INSERT INTO LINIA_ESCANDALL VALUES(4,3,1,4,1);
INSERT INTO LINIA_ESCANDALL VALUES(4,4,15,6,10);
INSERT INTO LINIA_ESCANDALL VALUES(4,5,1,4,13);

INSERT INTO LINIA_ESCANDALL VALUES(5,1,3,4,15);
INSERT INTO LINIA_ESCANDALL VALUES(5,2,6,6,7);
INSERT INTO LINIA_ESCANDALL VALUES(5,3,100,1,18);
INSERT INTO LINIA_ESCANDALL VALUES(5,4,250,1,8);

INSERT INTO LINIA_ESCANDALL VALUES(6,1,300,1,22);
INSERT INTO LINIA_ESCANDALL VALUES(6,2,250,1,9);

INSERT INTO LINIA_ESCANDALL VALUES(7,1,300,1,21);
INSERT INTO LINIA_ESCANDALL VALUES(7,2,200,1,23);
INSERT INTO LINIA_ESCANDALL VALUES(7,3,3,4,24);

INSERT INTO LINIA_ESCANDALL VALUES(8,1,40,1,2);
INSERT INTO LINIA_ESCANDALL VALUES(8,2,60,1,26);

INSERT INTO LINIA_ESCANDALL VALUES(9,1,40,1,21);
INSERT INTO LINIA_ESCANDALL VALUES(9,2,60,1,26);

INSERT INTO LINIA_ESCANDALL VALUES(10,1,6,4,16);
INSERT INTO LINIA_ESCANDALL VALUES(10,2,3,4,24);
INSERT INTO LINIA_ESCANDALL VALUES(10,3,50,1,17);
INSERT INTO LINIA_ESCANDALL VALUES(10,4,50,1,18);

INSERT INTO LINIA_ESCANDALL VALUES(11,1,250,1,25);
INSERT INTO LINIA_ESCANDALL VALUES(11,2,3,4,6);
INSERT INTO LINIA_ESCANDALL VALUES(11,3,50,1,23);

INSERT INTO TAULA VALUES(1);
INSERT INTO TAULA VALUES(2);
INSERT INTO TAULA VALUES(3);
INSERT INTO TAULA VALUES(4);
INSERT INTO TAULA VALUES(5);
INSERT INTO TAULA VALUES(6);
INSERT INTO TAULA VALUES(7);
INSERT INTO TAULA VALUES(8);
INSERT INTO TAULA VALUES(9);
INSERT INTO TAULA VALUES(10);

INSERT INTO CAMBRER VALUES(1,'Pere','Lopez','Garcia','plopez','plopez');
INSERT INTO CAMBRER VALUES(2,'Marta','Grau','Exposito','mgrau','mgrau');

INSERT INTO COMANDA VALUES(1,STR_TO_DATE('17/05/2021', '%d/%m/%Y'),1,1);
INSERT INTO COMANDA VALUES(2,STR_TO_DATE('18/05/2021', '%d/%m/%Y'),2,2);
INSERT INTO COMANDA VALUES(3,STR_TO_DATE('19/05/2021', '%d/%m/%Y'),3,1);
INSERT INTO COMANDA VALUES(4,STR_TO_DATE('20/05/2021', '%d/%m/%Y'),4,2);
INSERT INTO COMANDA VALUES(5,STR_TO_DATE('21/05/2021', '%d/%m/%Y'),1,1);

INSERT INTO LINIA_COMANDA VALUES(1,1,1,2,true);
INSERT INTO LINIA_COMANDA VALUES(1,2,2,3,true);
INSERT INTO LINIA_COMANDA VALUES(1,8,3,2,true);

INSERT INTO LINIA_COMANDA VALUES(2,5,1,1,true);
INSERT INTO LINIA_COMANDA VALUES(2,10,2,2,true);
INSERT INTO LINIA_COMANDA VALUES(2,7,3,3,true);
INSERT INTO LINIA_COMANDA VALUES(2,1,4,2,true);

INSERT INTO LINIA_COMANDA VALUES(3,6,1,2,true);
INSERT INTO LINIA_COMANDA VALUES(3,11,2,1,true);

INSERT INTO LINIA_COMANDA VALUES(4,8,1,3,true);
INSERT INTO LINIA_COMANDA VALUES(4,9,2,2,true);
INSERT INTO LINIA_COMANDA VALUES(4,7,3,1,true);


INSERT INTO LINIA_COMANDA VALUES(5,2,1,2,true);
INSERT INTO LINIA_COMANDA VALUES(5,3,2,1,true);
INSERT INTO LINIA_COMANDA VALUES(5,6,3,2,true);















