CREATE SCHEMA RESTAURANT;
USE RESTAURANT;

CREATE TABLE UNITAT (
	CODI MEDIUMINT(10) CHECK (CODI>0),
	NOM VARCHAR(40) NOT NULL,
    PRIMARY KEY(CODI)
);

CREATE TABLE INGREDIENT (
	CODI MEDIUMINT(10) CHECK (CODI>0),
	NOM VARCHAR(40) NOT NULL ,
    PRIMARY KEY(CODI)
);

CREATE TABLE CATEGORIA (
	CODI MEDIUMINT(10) CHECK (CODI>0),
	NOM VARCHAR(40) NOT NULL,
	COLOR VARCHAR(10) NOT NULL,
    PRIMARY KEY(CODI)
);

CREATE TABLE PLAT (
 	CODI MEDIUMINT(10) CHECK (CODI>0),              
 	NOM VARCHAR(50)  NOT NULL,
	DESCRIPCIO_MD VARCHAR(100)  NOT NULL,
	PREU DECIMAL(4,2) NOT NULL,
	FOTO MEDIUMBLOB NOT NULL,
	DISPONIBLE BOOLEAN NOT NULL,
	CATEGORIA MEDIUMINT(10) NOT NULL,
	PRIMARY KEY (CODI),   
    CONSTRAINT `PLAT_FK_CATEGORIA` FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (CODI)
);

CREATE TABLE LINIA_ESCANDALL (
	PLAT MEDIUMINT(10),
 	NUM SMALLINT(4) CHECK (NOT NULL AND NUM>0),              
 	QUANTITAT SMALLINT(4)  CHECK(NOT NULL AND QUANTITAT>0),
	UNITAT MEDIUMINT(10) NOT NULL, 
	INGREDIENT MEDIUMINT(10) NOT NULL,
	PRIMARY KEY (PLAT,NUM),   
    CONSTRAINT `LINIA_ESCANDALL_FK_UNITAT` FOREIGN KEY (UNITAT) REFERENCES UNITAT (CODI),
    CONSTRAINT `LINIA_ESCANDALL_FK_INGREDIENT` FOREIGN KEY (INGREDIENT) REFERENCES INGREDIENT (CODI),
    CONSTRAINT `LINIA_ESCANDALL_FK_PLAT` FOREIGN KEY (PLAT) REFERENCES PLAT (CODI)
      
);

CREATE TABLE TAULA(
	NUMERO SMALLINT (3),
	PRIMARY KEY (NUMERO)
);

CREATE TABLE CAMBRER (
	CODI MEDIUMINT(10),
	NOM VARCHAR(20) NOT NULL,
	COGNOM1 VARCHAR(20) NOT NULL,
	COGNOM2 VARCHAR(20),
	USER VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	PRIMARY KEY (CODI)
);

CREATE TABLE COMANDA (
 	CODI MEDIUMINT(10) CHECK (CODI>0),              
 	DATE DATE NOT NULL,
	TAULA SMALLINT(3) NOT NULL,
	CAMBRER MEDIUMINT(10) NOT NULL,
	PRIMARY KEY (CODI),   
    CONSTRAINT `COMANDA_FK_TAULA` FOREIGN KEY (TAULA) REFERENCES TAULA (NUMERO),
    CONSTRAINT `COMANDA_FK_CAMBRER` FOREIGN KEY (CAMBRER) REFERENCES CAMBRER (CODI)
);

CREATE TABLE LINIA_COMANDA (
	COMANDA MEDIUMINT(10),
	PLAT MEDIUMINT(10) NOT NULL,
 	NUM SMALLINT(4) CHECK (NOT NULL AND NUM>0),              
 	QUANTITAT SMALLINT(4)  CHECK(NOT NULL AND QUANTITAT>0),
	ACABAT BOOLEAN NOT NULL, 
	PRIMARY KEY (COMANDA,NUM),   
    CONSTRAINT `LINIA_COMANDA_FK_PLAT` FOREIGN KEY (PLAT) REFERENCES PLAT (CODI),
    CONSTRAINT `LINIA_COMANDA_FK_COMANDA` FOREIGN KEY (COMANDA) REFERENCES COMANDA (CODI)      
);
