CREATE SCHEMA RESTAURANT;
USE RESTAURANT;

CREATE TABLE UNITAT (
	CODI LONG(4) CHECK (CODI>0),
	NOM VARCHAR(40) NOT NULL ,
    PRIMARY KEY(CODI)
);

CREATE TABLE INGREDIENT (
	CODI LONG(4) CHECK (CODI>0),
	NOM VARCHAR(40) NOT NULL ,
    PRIMARY KEY(CODI)
);

CREATE TABLE CATEGORIA (
	CODI LONG(4) CHECK (CODI>0),
	NOM VARCHAR(40) NOT NULL,
	COLOR VARCHAR(10) NOT NULL,
    PRIMARY KEY(CODI)
);

CREATE TABLE PLAT (
 	CODI LONG(4) CHECK (CODI>0),              
 	NOM VARCHAR(50)  NOT NULL,
	DESCRIPCIO_MD VARCHAR(50)  NOT NULL,
	PREU BIGDECIMAL(4,2) NOT NULL,
	FOTO MEDIUMBLOB NOT NULL,
	DISPONIBLE INTEGER CHECK(NOT NULL AND (DISPONIBLE==1 OR DISPONIBLE==0)),
	CATEGORIA LONG(4) NOT NULL,
	PRIMARY KEY (CODI),   
    CONSTRAINT `PLAT_FK_CATEGORIA` FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (CODI)
);

CREATE TABLE LINIA_ESCANDALL (
	PLAT LONG(4)
 	NUM INTEGER(4) CHECK (NOT NULL AND NUM>0),              
 	QUANTITAT INTEGER(4)  CHECK(NOT NULL AND QUANTITAT>0),
	UNITAT LONG(4) NOT NULL 
	INGREDIENT LONG(4) NOT NULL  
	PRIMARY KEY (PLAT),   
    CONSTRAINT `LINIA_ESCANDALL_FK_UNITAT` FOREIGN KEY (UNITAT) REFERENCES UNITAT (CODI)
    CONSTRAINT `LINIA_ESCANDALL_FK_INGREDIENT` FOREIGN KEY (INGREDIENT) REFERENCES INGREDIENT (CODI)
    CONSTRAINT `LINIA_ESCANDALL_FK_PLAT` FOREIGN KEY (PLAT) REFERENCES PLAT (CODI)
      
);

CREATE TABLE TAULA(
	NUMERO INTEGER (3),
	PRIMARY KEY (NUMERO)
);

CREATE TABLE CAMBRER (
	CODI LONG(4),
	NOM VARCHAR(20) NOT NULL,
	COGNOM1 VARCHAR(20) NOT NULL,
	COGNOM2 VARCHAR(20),
	USER VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	PRIMARY KEY (CODI),   
);

CREATE TABLE COMANDA (
 	CODI LONG(4) CHECK (CODI>0),              
 	DATE DATE NOT NULL,
	TAULA INTEGER(3) NOT NULL,
	CAMBRER LONG(4) NOT NULL 
	PRIMARY KEY (CODI),   
    CONSTRAINT `COMANDA_FK_TAULA` FOREIGN KEY (TAULA) REFERENCES TAULA (NUMERO)
    CONSTRAINT `COMANDA_FK_CAMBRER` FOREIGN KEY (CAMBRER) REFERENCES CAMBRER (CODI)
);

CREATE TABLE LINIA_COMANDA (
	COMANDA LONG(4)
	PLAT LONG(4) NOT NULL
 	NUM INTEGER(4) CHECK (NOT NULL AND NUM>0),              
 	QUANTITAT INTEGER(4)  CHECK(NOT NULL AND QUANTITAT>0),
	ESTAT INTEGER CHECK(NOT NULL AND (ESTAT==1 OR ESTAT==0)), 
	PRIMARY KEY (COMANDA),   
    CONSTRAINT `LINIA_COMANDA_FK_PLAT` FOREIGN KEY (PLAT) REFERENCES PLAT (CODI)
    CONSTRAINT `LINIA_COMANDA_FK_COMANDA` FOREIGN KEY (COMANDA) REFERENCES COMANDA (CODI)      
);
